version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_apache_app
    restart: unless-stopped
    ports:
      - "8080:80"
      - "5173:5173"
    environment:
    # --- Fixas (não mudam entre devs) ---
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - ASSET_URL=http://localhost:8080
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      # --- Dinâmicas (o Docker pega do seu .env local) ---
      - APP_NAME=Laravel
      - APP_KEY="base64:Bvyi/hwxndoDA5XWq24sOsQ9MIcfFGQ4UQ8x0cmiGSU="
      - DB_HOST="laravel_db"
      - DB_PORT=5432
      - DB_DATABASE="laravel"
      - DB_USERNAME="postgres"
      - DB_PASSWORD="admin"
      # --- Drivers (Evita problemas de permissão de pasta no Windows) ---
      - SESSION_DRIVER=database
      - CACHE_STORE=database
    networks:
      - laravel-network
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB="laravel"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="admin"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
    driver: local