version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_apache_app
    restart: unless-stopped
    ports:
      - "8080:80"
      - "5173:5173"
    environment:
    # --- Fixas (não mudam entre devs) ---
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - ASSET_URL=http://localhost:8080
      - DB_CONNECTION=pgsql
      # --- Dinâmicas (o Docker pega do seu .env local) ---
      - APP_NAME=${APP_NAME}
      - APP_KEY=${APP_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # --- Drivers (Evita problemas de permissão de pasta no Windows) ---
      - SESSION_DRIVER=database
      - CACHE_STORE=database
    networks:
      - laravel-network
    depends_on:
      - db
  pgadmin:
    container_name: pg_admin_laravel
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@laravel.com.br
      PGADMIN_DEFAULT_PASSWORD: Laravel@2026
    ports:
      - 5050:80
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - laravel-network
  db:
    image: postgres:15-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  pgdata:
    driver: local